name: Build and publish Docker image

on:
  push:
    branches:
      - main

env:
  DOCKER_IMAGE_NAME: temphia_buildpack
  DOCKER_IMAGE_TAG: ${{ github.sha }}

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.TEMPHIA_BUILDPACK_ACTION }}

      - name: Build Docker image
        run: |
          docker build -t $DOCKER_IMAGE_NAME:$DOCKER_IMAGE_TAG .

      - name: Tag Docker image
        run: |
          docker tag $DOCKER_IMAGE_NAME:$DOCKER_IMAGE_TAG ghcr.io/${{ github.repository }}/$DOCKER_IMAGE_NAME:$DOCKER_IMAGE_TAG

      - name: Push Docker image
        run: |
          docker push ghcr.io/${{ github.repository }}/$DOCKER_IMAGE_NAME:$DOCKER_IMAGE_TAG
